name: CI
on:
  push:
    tags: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: env
        id: env
        run: |
          echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
          echo "::set-output name=DIR::ecl-${GITHUB_REF#refs/tags/}"
          echo "::set-output name=FILE::ecl-${GITHUB_REF#refs/tags/}-x86-64-linux-binary.tar.gz"
      - name: install
        run: |
          sudo apt update
          sudo apt install -y curl gcc

      - name: checkout
        uses: actions/checkout@v2

      - name: build_ecl
        run: |
          export VERSION=${GITHUB_REF#refs/tags/}
          curl -L https://common-lisp.net/project/ecl/static/files/release/ecl-$VERSION.tgz --output ecl-$VERSION.tgz
          tar -xvzf ecl-$VERSION.tgz
          cd ecl-$VERSION
          mkdir build
          # ./configure
          # make -j2
          # sudo make install

      # - name: test
      #   run: |
      #     ecl --eval '(quit)'
      #     ecl --help

      - name: archive
        run: |
         tar czf ${{ steps.env.outputs.FILE }} ${{ steps.env.outputs.DIR }}/build

      - name: release
        id: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.env.outputs.FILE }}
          path: ${{ steps.env.outputs.FILE }}

      - name: upload
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: ${{ steps.env.outputs.FILE }}
